title: FGBackup Documentation
description: Official documentation for FGBackup, an open-source Fortinet backup automation tool.
theme: minima
baseurl: "/FGBackup"
url: "https://alpha3cloud.github.io"
markdown: kramdown
